version: 2

multi-ecosystem-groups:
  weekly-updates:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "weekly-updates"
    patterns: ["*"]
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "weekly-updates"
    patterns: ["*"]
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "uv"
    directory: "/"
    patterns: ["*"]
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
